version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.34.8
    depends_on:
      - mysql
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - ./persistance/mysql:/var/lib/mysql
